stages:
  - build

include:
  - local: '/ci/jobs/build/build.yml'

pages:
  stage: .post
  image: circleci/node:16-bullseye-browsers-legacy
  cache:
    paths:
    - node_modules/
  script:
  - npm install -g @angular/cli@14.2.2
  - npm install
  - ng build --prod --base-href /frontend-bootcamp/
  - mkdir -p public
  - mv dist/frontend-bootcamp/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages